"""Sound Bath Calendar — shared entity presence (CAL-29).

The three entity families (practitioner · venue · operator) share ONE face in
the v5 Broadcast register:

  * a PORTRAIT — the entity's own committed photo as the same indigo duotone
    square the Program Grid cards ride (`img/entities/<stem>-i.jpg`, coral
    `-c` crossfade on hover), generated by scripts/treat.py;
  * or a TYPE-PLATE — a `--surface` square carrying the entity's initial
    letterform in condensed 800. A designed poster variant, not a fallback
    state, and never a session flyer: **flyers never stand in for faces**
    (imagery law, DESIGN.md §4).

The three directory indexes render that face in the CAL-28 card anatomy, so
/practitioners/, /venues/ and /operators/ read as the same program grid as the
calendar itself. The styles live in styles.css (`.cal-card*`, `.plate`,
`.ent-*`) since every entity template rides them; this module holds the render
helpers so the markup can never drift apart between the three renderers.
"""

from _src.lib import external_events as X

_esc = X._esc

# Entity portrait stems with committed derivatives (build.py registers the
# contents of img/entities/ before any entity renders — same contract as
# external_events.set_card_art).
_ENT_ART = set()

# Only practitioners have a portrait pipeline. Venue photographs are Google
# Places imagery (terms: resize/crop yes, recolor no) so venues plate here and
# keep their unmodified photo on the profile page; operators have no photo of
# their own at all. See scripts/treat.py:treat_entities.
_KIND_PREFIX = {'practitioner': 'pract'}


def set_entity_art(stems):
    """Register the set of committed entity-portrait stems (CAL-29)."""
    global _ENT_ART
    _ENT_ART = set(stems or ())


def art_stem(kind, slug):
    """`pract-<slug>` / `venue-<slug>` — or '' for a family with no portrait
    pipeline (operators carry no photo of their own; they always plate)."""
    prefix = _KIND_PREFIX.get(kind)
    return f'{prefix}-{slug}' if prefix and slug else ''


def has_portrait(kind, slug):
    return art_stem(kind, slug) in _ENT_ART


def _initial(name):
    return (name or '?').strip()[:1].upper()


def portrait_html(kind, slug, name, nav_prefix, cls='', sizes='200px',
                  eager=False):
    """The entity's face: the duotone pair when a committed portrait exists,
    else the type-plate. `cls` places it (`.cal-card__im` inside a card,
    `.ent-portrait` in a profile head). The image is alt=""/aria-hidden — the
    name beside or below it carries the meaning."""
    stem = art_stem(kind, slug)
    if stem in _ENT_ART:
        p = f'{nav_prefix}img/entities/{stem}'
        loading = 'eager' if eager else 'lazy'
        return (
            f'<span class="{cls}">'
            f'<img src="{_esc(p)}-i.jpg" '
            f'srcset="{_esc(p)}-i280.jpg 280w, {_esc(p)}-i.jpg 560w" '
            f'sizes="{_esc(sizes)}" width="560" height="560" alt="" '
            f'loading="{loading}" decoding="async">'
            f'<img class="cal-card__im-c" src="{_esc(p)}-c.jpg" width="560" '
            f'height="560" alt="" loading="lazy" decoding="async" '
            f'aria-hidden="true"></span>')
    return (f'<span class="{cls} plate" data-initial="{_esc(_initial(name))}" '
            f'aria-hidden="true"></span>')


def render_head(nav_prefix, crumb_label, h1, lede):
    """The directory index head — left-set monument (v5 retires the centered
    identity block and the eyebrow), crumb above it as chrome."""
    return (
        f'    <nav class="dir-crumbs" aria-label="Breadcrumb">\n'
        f'      <a href="{nav_prefix}">Calendar</a> <span aria-hidden="true">/</span> '
        f'<span>{_esc(crumb_label)}</span>\n'
        f'    </nav>\n'
        f'    <div class="dir-head">\n'
        f'      <h1 class="dir-h1">{_esc(h1)}</h1>\n'
        f'      <p class="dir-lede">{_esc(lede)}</p>\n'
        f'    </div>')


def render_card(href, name, meta, kind, slug, nav_prefix):
    """One directory card, in the CAL-28 card anatomy: the face on top, then
    the caption (h3 > a name, underlined at rest and stretched over the whole
    card via CSS ::after, then one --muted meta line)."""
    face = portrait_html(
        kind, slug, name, nav_prefix, cls='cal-card__im',
        sizes='(max-width: 719px) 46vw, (max-width: 1023px) 30vw, 23vw')
    return (
        f'      <article class="cal-card dir-card">\n'
        f'        {face}\n'
        f'        <span class="cal-card__cap">\n'
        f'          <h3 class="cal-row__name"><a href="{_esc(href)}">{_esc(name)}</a></h3>\n'
        f'          <p class="cal-card__meta">{_esc(meta)}</p>\n'
        f'        </span>\n'
        f'      </article>')


def render_grid(cards):
    """The directory program grid — 4-up at desktop, the shared card tracks."""
    inner = '\n'.join(cards)
    return f'    <div class="cal-rows cal-rows--4">\n{inner}\n    </div>'


# ---------------------------------------------------------------------------
# Profile heads (practitioner / venue / operator) — one anatomy, three callers
# ---------------------------------------------------------------------------

def render_entity_head(kind, slug, name, plays, nav_prefix):
    """Name opens the page (no eyebrow, no kicker — standing ruling), beside
    the portrait/plate; the one --muted 'plays' line sits under the name."""
    face = portrait_html(kind, slug, name, nav_prefix, cls='ent-portrait',
                         sizes='200px', eager=True)
    out = ['    <div class="ent-head">', f'      {face}',
           '      <div class="ent-headtext">',
           f'        <h1 class="detail__h1">{_esc(name)}</h1>']
    if plays:
        out.append(f'        <p class="ent-plays">{plays}</p>')
    out.append('      </div>')
    out.append('    </div>')
    return '\n'.join(out)


# The pull-quote is REAL QUOTED TEXT ONLY (CAL-29): a span the source actually
# put in quotation marks. Nothing is composed for the design's sake — and the
# span has to be a WHOLE thought, not a fragment. The bios quote-mark plenty of
# mid-sentence phrases ("…is not what has got me through my 40's onwards"),
# and pulling one of those out at 24px would misrepresent the person. So the
# filter is deliberately narrow: begins on a capital, ≥7 words, and never
# longer than a line-and-a-half of display type. A profile that doesn't clear
# the bar simply has no pull-quote.
_QUOTE_MIN, _QUOTE_MAX = 45, 220
_QUOTE_MIN_WORDS = 7


def pull_quote(text):
    """The first genuinely quoted WHOLE thought in `text`, or ''."""
    src = text or ''
    for open_q, close_q in (('“', '”'), ('"', '"')):
        start = src.find(open_q)
        while start != -1:
            end = src.find(close_q, start + 1)
            if end == -1:
                break
            # An inline attributed quote often ends mid-sentence ("…," she
            # says) — the pulled line drops that hanging punctuation.
            span = src[start + 1:end].strip().rstrip(',;: ')
            if (_QUOTE_MIN <= len(span) <= _QUOTE_MAX
                    and span[:1].isupper()
                    and len(span.split()) >= _QUOTE_MIN_WORDS):
                return span
            start = src.find(open_q, end + 1)
    return ''


def render_pull_quote(text):
    """The quote, set as the page's one condensed 24 voice — or nothing."""
    q = pull_quote(text)
    return (f'    <p class="ent-quote">“{_esc(q)}”</p>') if q else ''
